"""
Django settings for product_assistant project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from mongoengine import connect

# MONGO_DB_NAME = "ai_assistant"
# MONGO_HOST = "localhost"  # If using a local MongoDB
# MONGO_PORT = 27017        # Default MongoDB port

# # If using authentication
# MONGO_USER = "your_username"
# MONGO_PASSWORD = "your_password"

# # Connect to MongoDB
# connect(
#     db=MONGO_DB_NAME,
#     host=MONGO_HOST,
#     port=MONGO_PORT,
#     # username=MONGO_USER,  # Remove if not using authentication
#     # password=MONGO_PASSWORD,  # Remove if not using authentication
#     # authentication_source="admin"  # Change if needed
# )

MONGODB_HOST = "mongodb+srv://techteam:Tech!123@dataextraction.h6crc.mongodb.net/"
MONGODB_NAME = "ai_assistant"
connect(
    db=MONGODB_NAME,
    host=MONGODB_HOST,
    alias="default"
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q2f1mgv^0h6j_5b=*p9s*s%vyjnvh7sa*(q$-k+&ih%i!9o$pu'

DEBUG = True

ALLOWED_HOSTS = ["*"]

CORS_ALLOW_ALL_ORIGINS = True
# CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://guided-selling-assistant.onrender.com",
    "https://guided-selling-bot-frontend.vercel.app"
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "https://guided-selling-assistant.onrender.com",
    "https://guided-selling-bot-frontend.vercel.app"
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'guidedProductAssistant',
    'corsheaders',
    'rest_framework',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'product_assistant.custom_mideleware.customMiddleware' #custom middle ware
]

ROOT_URLCONF = 'product_assistant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'product_assistant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OPEN_AI_KEY = "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"